services:
  - type: web
    name: paint-numbers-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    autoDeploy: false
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://paint-number-generator-56al.vercel.app
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
